# Copyright (c) 2025, WSO2 LLC. (http://www.wso2.org).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: "WSO2 Integrator: WebSubHub Documentation"
site_description: "Documentation for WSO2 Integrator: WebSubHub"
site_author: WSO2
site_url: https://websubhub.docs.wso2.com/

# Repository information
repo_name: wso2/docs-websubhub
repo_url: https://github.com/wso2/docs-websubhub
edit_uri: https://github.com/wso2/docs-websubhub/edit/main/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: "WSO2 Integrator: WebSubHub - Documentation"

# Configuration
theme:
  name: material
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/bi-logo.svg
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.path
    - navigation.top
  #highlightjs: true
  feature:
    tabs: true
  language: 'en'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Strict Mode
strict: false # Set to true to break the build if there are warnings

# Navigation structure
nav:
  - Home: index.md
  # - Get started:
  #     - Quick Start Guide: get-started/quick-start-guide.md
  #     - "Install WSO2 Integrator: BI": get-started/install-wso2-integrator-bi.md
  #     - Develop Integrations:
  #       - Develop Automation: get-started/develop-automation.md
  #       - Develop AI Agent: get-started/develop-ai-agent.md
  #       - Develop Integration as API: get-started/develop-integration-as-api.md
  #       - Develop Event Integration: get-started/develop-event-integration.md
  #       - Develop File Integration: get-started/develop-file-integration.md
  # - Integration Guides:
  #     - AI Agents and Other Gen AI Integrations:
  #       - Direct LLM Invocation:
  #         - Natural functions(Beta): integration-guides/ai/natural-functions/natural-functions.md
  #         - Model providers: integration-guides/ai/direct-llm-call/direct-llm-invocation-with-ballerina-model-providers.md
  #       - RAG:
  #         - Rag Ingestion: integration-guides/ai/rag/rag-ingestion.md
  #         - Rag Query: integration-guides/ai/rag/rag-query.md
  #       - Agents:
  #         - integration-guides/ai/agents/index.md
  #         - Introduction to Chat Agents: integration-guides/ai/agents/introduction-to-chat-agents.md
  #         - Introduction to Inline Agents: integration-guides/ai/agents/introduction-to-inline-agents.md
  #         - Integrating Agents with MCP Servers: integration-guides/ai/agents/integrating-agents-with-mcp-servers.md
  #         - Integrating Agents with External Endpoints: integration-guides/ai/agents/integrating-agents-with-external-endpoints.md
  #     - Integration As API:
  #       - Service Orchestration: integration-guides/integration-as-api/service-orchestration.md
  #       - Message Transformation: integration-guides/integration-as-api/message-transformation.md
  #       - Message Routing: integration-guides/integration-as-api/message-routing.md
  #     - File Integration:
  #       - File Integration With Directory Service: integration-guides/file-integration/file-integration-with-directory-service.md
  # - Developer Guides:
  #     - Create a Project: developer-guides/create-a-project.md
  #     - "WSO2 Integrator: BI Artifacts": developer-guides/wso2-integrator-bi-artifacts.md
  #     - Design the Integrations: developer-guides/design-the-integrations.md
  #     - Data Mapping: developer-guides/data-mapping.md
  #     - Try the Integration: developer-guides/try-the-integration.md
  #     - Testing: developer-guides/test-the-integrations.md
  #     - Debugging & Troubleshooting:
  #         Overview: developer-guides/debugging-and-troubleshooting/overview.md
  #         Debugging within the Editor: developer-guides/debugging-and-troubleshooting/debugging-within-the-editor.md
  #         Remote Debugging Integrations: developer-guides/debugging-and-troubleshooting/remote-debugging-integrations.md
  #         Capturing Strand Dumps: developer-guides/debugging-and-troubleshooting/capturing-strand-dumps.md
  #         Profiling Runtime Performance: developer-guides/debugging-and-troubleshooting/profiling-runtime-performance.md
  #     - AI For Integration:
  #       - Build an HTTP Service With WSO2 Copilot : developer-guides/ai-for-integration/build-an-http-service-with-wso2-copilot.md
  #     - Protocols and Connectors:
  #       - Overview of Connectors: developer-guides/protocols-and-connectors/overview-of-connectors.md
  #       - Supported Protocols: developer-guides/protocols-and-connectors/supported-protocols.md
  #       - Build Local Connectors: developer-guides/protocols-and-connectors/build-local-connectors.md
  #     - Tools:
  #       - Migration Tools:
  #         - Mulesoft Migration Tool: developer-guides/tools/migration-tools/mulesoft-migration-tool.md
  #         - TIBCO BusinessWorks Migration Tool: developer-guides/tools/migration-tools/tibco-businessworks-migration-tool.md
  #         - Azure Logic Apps Migration Tool: developer-guides/tools/migration-tools/logic-apps-migration-tool.md
  #       - Integration Tools:
  #         - Health Tool: developer-guides/tools/integration-tools/health-tool.md
  #         - EDI Tool: developer-guides/tools/integration-tools/edi-tool.md
  #       - Other Tools:
  #         - Scan Tool: developer-guides/tools/other-tools/scan-tool.md
  # - Deploy:
  #     - Overview: deploy/overview.md
  #     - Deploy to Devant: deploy/deploy-to-devant.md
  #     - Containerized Deployment:
  #       - Overview: deploy/containerized-deployment/overview.md
  #       - Deploy as Docker Image: deploy/containerized-deployment/deploy-as-docker-image.md
  #       - Deploy on Kubernetes: deploy/containerized-deployment/deploy-on-kubernetes.md
  #     - VM-based Deployment:
  #       - Overview: deploy/vm-based-deployment/overview.md
  #       - Deploy on VM as Executable JAR: deploy/vm-based-deployment/deploy-on-vm-as-executable-jar.md
  #       - Centralized Deployment: deploy/vm-based-deployment/centralized-deployment.md
  #       - Decentralized Deployment: deploy/vm-based-deployment/de-centralized-deployment.md
  #       - GitHub Action for CICD: deploy/vm-based-deployment/github-action-for-cicd.md
  #     - Managing configurations: deploy/managing-configurations.md
  #     - Capacity Planning:
  #       - Overview: deploy/capacity-planning/overview.md
  #       - Performance Report for REST Services: deploy/capacity-planning/performance-report-for-rest-services.md
  # - Observability and Monitoring:
  #     - Overview: observability-and-monitoring/overview.md
  #     - "Monitoring with WSO2 Integrator: ICP": observability-and-monitoring/monitoring-with-wso2-integrator-icp.md
  #     - Observability with Devant: observability-and-monitoring/observability-with-devant.md
  #     - Supported Observability Tools and Platforms:
  #       - Overview: observability-and-monitoring/supported-observability-tools-and-platforms/overview.md
  #       - Prometheus: observability-and-monitoring/supported-observability-tools-and-platforms/prometheus.md
  #       - Jaeger: observability-and-monitoring/supported-observability-tools-and-platforms/jaeger.md
  #       - Zipkin: observability-and-monitoring/supported-observability-tools-and-platforms/zipkin.md
  #       - New Relic: observability-and-monitoring/supported-observability-tools-and-platforms/new-relic.md
  #       - Datadog: observability-and-monitoring/supported-observability-tools-and-platforms/datadog.md
  #       - Elastic Stack: observability-and-monitoring/supported-observability-tools-and-platforms/elastic-stack.md
  #       - OpenSearch: observability-and-monitoring/supported-observability-tools-and-platforms/opensearch.md
  # - References:
  #     - "Enterprise Integrations Patterns": references/enterprise-integrations-patterns.md
  #     - "System Requirements": references/system-requirements.md
      

# Markdown extensions configuration
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list

# Plugins configuration
plugins:
  - search
  - markdownextradata: {}
  - exclude:
      glob:
        - wip/*
  - redirects:
      redirect_maps:

# Extra configuration
extra_css:
  # You can select a different theme for syntax highlighting by simply
  # selecting a different css file below from the available list.
  - assets/lib/highlightjs/styles/vs.min.css
  # Make sure to activate only one palette at a time.
  # If all the palettes are commented out, the default material theme palette will take over
  - assets/css/blue-palette-alt1.css
  # - assets/css/blue-palette-alt2.css
  # - assets/css/blue-palette.css
  # - assets/css/green-palette.css
  # - assets/css/orange-palette.css
  - assets/css/mitheme.css
  - assets/css/custom.css
  - assets/lib/json-formatter/json-formatter.css
  - assets/css/config-catalog.css
  - assets/lib/fontawesome-free-6.3.0-web/css/all.min.css
#  - assets/css/redoc.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/js/mitheme.js
  # - assets/lib/backtotop/js/util.js
  # - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  # site_version: Uncomment to specify a version
  base_path: https://wso2.github.io/docs-websubhub
  # base_path: http://localhost:8000
